config/routes.rb
Rails.application.routes.draw do

  # get 'subs/index', :to => 'subs#index'
  root 'subs#index'
  
  resources :subs do
    resources :topics
  end

  scope 'topics/:topic_id', as: 'topic' do
    resources :comments, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
end

app/models/sub.rb
class Sub < ApplicationRecord
  has_many :topics, dependent: :destroy
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :sub
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_topic
  
  def new
    @comments = Comment.new
    render partial: "form"
  end

  def create
    @comments = @topics.comments.new(comment_params)

    if @comments.save
      redirect_to sub_topic_path(@topics.sub_id, @topics)
    else
      render :new
    end
  end

private

def set_topic
  @topics = Topic.find(params[:topic_id])
end

def comment_params
  params.require(:comment).permit(:body, :author)
end


end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_subs, only: [:show, :update, :edit, :destroy]
  
  def index
    @subs = Sub.all
  end

  def show
  end

  def new
    @subs = Sub.new
    render partial: 'form'
  end

  def create
    @subs = Sub.new(sub_params)
    if @subs.save
      redirect_to subs_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @subs.update(sub_params)
      redirect_to @subs
    else
      redirect :edit
    end
  end

  def destroy
    @subs.destroy
    redirect_to subs_path
  end

private

def set_subs
  @subs = Sub.find(params[:id])
end

def sub_params
  params.require(:sub).permit(:name)
end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_subs
  before_action :set_topics, only: [:show, :edit, :update, :destroy]
  
  def index
    @topics = @subs.topics
  end

  def show
  end

  def new
    @topics = @subs.topics.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @topics = @subs.topics.new(topic_params)
    if @topics.save
      redirect_to [@subs, @topics]
    else
      render :new
    end
  end

  def update
    if @topics.update(topic_params)
      redirect_to [@subs, @topics]
    else
      render :edit
    end
  end

  def destroy
    @topics.destroy
    redirect_to sub_topics_path
  end


private

def set_subs
  @subs = Sub.find(params[:sub_id])
end

def set_topics
  @topics = Topic.find(params[:id])
end

def topic_params
  params.require(:topic).permit(:body, :name)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.erb
<hr/>
<p>Author: <%=comment.author %></p>
<p>Body: <%= comment.body %></p>
<hr/>

app/views/comments/_form.html.erb
<h1>Create new comment</h1>
<hr/>
<%= form_for [@topics, @comments] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true, autofocus: true %>
  <br/>
  <%= f.label :author %>
  <%= f.text_field :author, required: true %>
  <%= f.submit %>
  <% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/_form.html.erb
<h1><%= @subs.id ? 'Edit Sub' : 'Create Sub' %></h1>
<hr/>
<%= form_for @subs do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
  <% end %>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1> Welcome to Reddit</h1>
<h3>Please select a Sub-Reddit</h3>

<%= link_to 'Create a new sub', new_sub_path %>

<ul>
  <% @subs.each do |sub| %>
    <li><%= link_to sub.name, sub_path(sub) %></li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>

app/views/subs/show.html.erb
<h1><%=@subs.name%></h1>
<hr/>
<p>What would you like to do?</p>
<%= link_to 'View topics', sub_topics_path(@subs) %>
<br/>
<%= link_to 'Edit Sub', edit_sub_path(@subs) %>
<br/>
<%= link_to 'Delete Sub', @subs, method: :delete %>

app/views/topics/_form.html.erb
<h1><%= @topics.id ? 'Edit Topic' : 'Create Topic' %></h1>
<hr/>
<%= form_for [@subs, @topics] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br/>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
  <% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Click a Topic to view Content</h1>

<%= link_to 'Create a new Topic', new_sub_topic_path(@subs) %>

<ul>
  <% @topics.each do |topic| %>
    <li><%= link_to topic.name, [@subs, topic] %></li>
    <% end %>
</ul>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1><%= @subs.name %> - <%=@topics.name %> </h1>
<p> <%= @topics.body %>
<h2>Comments</h2>

<% @topics.comments.each do |comment| %>
<%= render 'comments/comment', {comment: comment} %>
<% end %>

<hr/>
<%= link_to 'Add Comment', new_topic_comment_path(@topics) %>
<%= link_to 'Edit Topic', edit_sub_topic_path([@subs, @topics]) %>
<%= link_to 'Delete Topic', [@subs, @topics], method: :delete %>
<%= link_to 'Back TO Topics', sub_topics_path(@subs) %>